import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import {build} from 'esbuild';

test('stepping retains last pause, expansions and stable source; stale controls are disabled', async t => {
 const html = await readFile('packages/web/public/index.html','utf8');
 const js = await build({entryPoints:['packages/web/src/app.ts'],bundle:true,write:false,format:'iife',logLevel:'silent'});
 const dom = new JSDOM(html,{url:'http://127.0.0.1:1234',runScripts:'outside-only'});
 t.after(()=>dom.window.close());
 const w=dom.window,d=w.document;
 let tick, fail=false;
 let state={id:'test',owner:'browser',generation:1,status:'paused',state:{Pid:1},project:'/demo',binary:'/demo/bin',sourceIdentity:{match:'mismatch'},frame:0,goroutine:1,goroutines:[{id:1}],frames:[{file:'main.go',line:18,function:{name:'main.process'},Locals:[{name:'value',type:'S',children:[{name:'n',type:'int',value:'21'}]}]}],source:{file:'main.go',start:18,line:18,lines:['total += delta']}};
 w.setInterval=fn=>{tick=fn;return 1;};
 const calls=[];
 w.fetch=async(url,options)=>{url=new URL(url,w.location.href).pathname+new URL(url,w.location.href).search;calls.push({url,options});if(url==='/api/action')return {ok:true,json:async()=>JSON.parse(options.body).action==='eval'?{value:{name:'value',type:'S',children:[{name:'n',type:'int',value:'42'}]},generation:state.generation,goroutine:state.goroutine,frame:state.frame}:{Breakpoint:{file:'main.go',line:23}}};if(url.startsWith('/api/sources?'))return {ok:true,json:async()=>({file:'/demo/other.go',start:1,line:0,lines:['package main','func other() {}']})};if(url==='/api/sources')return {ok:true,json:async()=>({files:['/demo/other.go']})};if(url==='/api/sessions')return {ok:true,json:async()=>({sessions:[{id:'test',project:'/demo',binary:'/demo/bin',status:'paused',owner:'browser',panel:'http://127.0.0.1:1234/'},{id:'other',project:'/other',binary:'/other/app',status:'paused',owner:'agent',binding:{name:'Pi'},panel:'http://127.0.0.1:5678/'},{id:'offline',project:'/old',binary:'/old/app',status:'offline'}]})};if(fail)throw Error('offline');return {ok:true,json:async()=>structuredClone(state)};};
 const flush=()=>new Promise(r=>setTimeout(r,0));
 w.eval(js.outputFiles[0].text);await flush();
 d.querySelector('#refreshSessions').click();await flush();
 assert.equal(d.querySelectorAll('.sessionRow').length,3);
 assert.equal(d.querySelectorAll('.endSession').length,2);
 w.confirm=()=>false;d.querySelector('.endSession').click();await flush();
 assert.ok(calls.every(c=>c.options.method==='GET'),'cancel must not terminate');
 assert.equal(d.querySelector('#sessionList a').href,'http://127.0.0.1:5678/');
 assert.match(d.querySelector('#sessionList').textContent,/Current/);
 assert.ok(calls.every(c=>c.options.method==='GET'),'listing must not mutate session');
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
 w.HTMLDialogElement.prototype.close=function(){this.open=false;};
 d.querySelector('#openFile').click();await flush();
 d.querySelector('.fileResult').click();await flush();
 assert.equal(d.querySelectorAll('[role=tab]').length,2);
 assert.match(d.querySelector('#filename').textContent,/other.go/);
 assert.match(d.querySelector('#frameName').textContent,/main.process/,'browsing must preserve locals scope');
 tick();await flush();assert.match(d.querySelector('#filename').textContent,/other.go/,'polling must not steal active tab');
 d.querySelector('#followSource').click();
 const source=d.querySelector('.sourceContent'),details=d.querySelector('#locals details'),frame=d.querySelector('#frames button');
 details.open=true;
 state={...state,status:'running',generation:2,frames:undefined,source:undefined,sourceIdentity:undefined,state:{}};tick();await flush();
 assert.equal(d.querySelector('.sourceContent'),source);
 assert.equal(d.querySelector('#locals details'),details);
 assert.equal(frame.disabled,true);
 assert.equal(d.querySelector('#sourceWarning').hidden,false,'warning must keep its space during a step');
 assert.match(d.querySelector('#session').textContent,/PID 1/);
 assert.equal(d.querySelector('main').dataset.executing,'true');
 assert.match(d.querySelector('#stopReason').textContent,/last pause/);
 state={...state,status:'paused',frames:[{file:'main.go',line:18,function:{name:'main.process'},Locals:[{name:'value',type:'S',children:[{name:'n',type:'int',value:'42'}]}]}],source:{file:'main.go',start:18,line:18,lines:['total += delta']}};tick();await flush();
 assert.equal(d.querySelector('.sourceContent'),source);
 assert.equal(d.querySelector('#locals details').open,true);
 assert.match(d.querySelector('#locals').textContent,/42/);
 assert.equal(d.querySelector('#frames button').disabled,false);
 const lines=Array.from({length:27},(_,i)=>'// line '+(i+10));
 state={...state,source:{file:'main.go',start:10,line:22,lines}};tick();await flush();
 const stableCode=d.querySelector('.sourceContent');
 state={...state,generation:3,source:{file:'main.go',start:11,line:23,lines:[...lines.slice(1),'// line 37']}};tick();await flush();
 assert.equal(d.querySelector('.sourceContent'),stableCode,'overlapping step should move marker without replacing code');
 assert.equal(d.querySelector('.sourceHighlight.current').dataset.line,'23');
 fail=true;tick();await flush();assert.equal(d.querySelector('.sourceContent'),stableCode);assert.equal(d.querySelector('#frames button').disabled,true);
 fail=false;tick();await flush();assert.equal(d.querySelector('#frames button').disabled,false);
 assert.equal(d.querySelector('.sourceNumber[data-line="23"]').tagName,'DIV');
 assert.equal(d.querySelector('.sourceNumber[data-line="23"] .lineLabel').textContent,'23');
 state={...state,owner:'agent'};tick();await flush();
 assert.equal(d.querySelector('.breakpointGutter[data-line="23"]').disabled,false);
 assert.equal(d.querySelector('[data-action=step]').disabled,true);
 assert.equal(d.querySelector('#takeBrowser').disabled,false);
 d.querySelector('.breakpointGutter[data-line="23"]').click();await flush();
 const action=JSON.parse(calls.find(c=>c.url==='/api/action').options.body);
 assert.equal(action.action,'break');assert.equal(action.file,'main.go');assert.equal(action.line,23);
 assert.equal(action.generation,3);assert.equal(action.actor,'browser');
 assert.match(d.querySelector('#notice').textContent,/main.go:23/);
 d.querySelector('#source').scrollTop=200;
 state={...state,breakpoints:[{id:2,file:'/demo/other.go',line:2},{id:1,file:'main.go',line:23}]};tick();await flush();
 assert.equal(d.querySelector('#source').scrollTop,200,'breakpoint refresh must not recenter the paused line');
 d.querySelector('.breakpointLink').click();await flush();
 assert.match(d.querySelector('#filename').textContent,/other.go/);
 assert.equal(d.querySelector('.sourceHighlight.navigated').dataset.line,'2');
 assert.match(d.querySelector('#frameName').textContent,/main.process/);
 const revealed=[];
 w.HTMLElement.prototype.scrollIntoView=function(){revealed.push(this.id);};
 assert.equal(d.querySelector('#locals .inspect'),null);
 d.querySelector('#expression').value='value';
 d.querySelector('#evaluate').click();await flush();
 assert.match(d.querySelector('#evaluation').textContent,/42/);
 assert.equal(d.querySelector('#evaluation details').open,true);
 assert.ok(revealed.includes('evaluation'));
 assert.equal(d.querySelector('#addWatch').hidden,false);
 const evaluationCall=JSON.parse(calls.at(-2).options.body || '{}');
 assert.equal(evaluationCall.action,'eval');
 assert.equal(evaluationCall.frame,state.frame);
 state={...state,owner:'browser',frames:[{file:'main.go',line:18,function:{name:'main.process'},Locals:[{name:'value',type:'S',kind:25,len:2,children:[{name:'n',type:'int',value:'21'}]}]}]};tick();await flush();
 assert.equal(d.querySelector('#locals .pinButton').getAttribute('aria-pressed'),'false');
 const localOpen=d.querySelector('#locals details').open;
 d.querySelector('#locals .pinButton').click();await flush();
 assert.equal(d.querySelector('#locals details').open,localOpen,'pinning must not toggle expansion');
 const pinAction=JSON.parse(calls.filter(c=>c.url==='/api/action').at(-1).options.body);
 assert.equal(pinAction.action,'watch');assert.equal(pinAction.expression,'value');
 d.querySelector('#locals .loadMore').click();await flush();
 assert.match(d.querySelector('#locals').textContent,/42/,'load more replaces the inline value');
 assert.equal(d.querySelector('#locals details').open,true);
 d.querySelector('#expression').value='edited input';
 d.querySelector('#addWatch').click();await flush();
 assert.equal(JSON.parse(calls.filter(c=>c.url==='/api/action').at(-1).options.body).expression,'value','save uses the evaluated expression, not edited input');
 state={...state,watches:[{expression:'value',value:{name:'value',type:'int',value:'42'}}]};tick();await flush();
 assert.equal(d.querySelector('#evaluation').hidden,true,'pinned results are not duplicated');
 assert.equal(d.querySelector('#addWatch').hidden,true);
 assert.match(d.querySelector('#watches').textContent,/42/);
 assert.equal(d.querySelector('#locals .pinButton').getAttribute('aria-pressed'),'true');
 d.querySelector('#locals .pinButton').click();await flush();
 assert.equal(JSON.parse(calls.filter(c=>c.url==='/api/action').at(-1).options.body).action,'unwatch');
 d.querySelector('#watches button').click();await flush();
 const unpin=JSON.parse(calls.filter(c=>c.url==='/api/action').at(-1).options.body);
 assert.equal(unpin.action,'unwatch');
 assert.equal(unpin.expression,'value');


});
