import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import {build} from 'esbuild';

test('workspace distinguishes disconnected debugger from ended run and stops without an agent',async t=>{
 const html=await readFile('packages/web/public/index.html','utf8');const js=await build({entryPoints:['packages/web/src/workspace.ts'],bundle:true,write:false,format:'iife',globalName:'Workspace',logLevel:'silent'});const dom=new JSDOM(html,{url:'http://127.0.0.1:1234/?session=1111111111',runScripts:'outside-only'});t.after(()=>dom.window.close());const w=dom.window,d=w.document;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.eval(js.outputFiles[0].text+';window.W=Workspace;');const requests=[];let ended=false;const request=async(path,body)=>{requests.push({path,body});if(path==='workspace')return {investigations:[{id:'1111111111',title:'Investigate total',project:'/demo',runs:[{id:'1111111111',binary:'/demo/app',project:'/demo',status:'paused',panel:'http://127.0.0.1:1234/?session=1111111111'}]}]};return {}};const ui=w.W.createWorkspace({request,history:()=>{},ended:()=>ended=true});const state={id:'1111111111',project:'/demo',binary:'/demo/app',status:'paused',state:{Pid:42},binding:{name:'Pi'},agentConnected:false};ui.update(state);await new Promise(r=>setTimeout(r,0));assert.match(d.querySelector('#investigationPicker').textContent,/Investigate total/);assert.equal(d.querySelector('#stop').disabled,false);ui.update(state,true);assert.match(d.querySelector('#status').textContent,/Connection lost/);d.querySelector('#stop').click();assert.match(d.querySelector('#workspaceDialogBody').textContent,/recover 1111111111/);assert.equal(requests.some(r=>r.body),false);
 d.querySelector('#closeWorkspaceDialog').click();ui.update(state);d.querySelector('#stop').click();[...d.querySelectorAll('#workspaceDialogBody button')].find(b=>b.textContent==='End run').click();await new Promise(r=>setTimeout(r,0));assert.equal(ended,true);assert.deepEqual(JSON.parse(JSON.stringify(requests.find(r=>r.path==='sessions/stop').body)),{id:'1111111111',confirmed:true});ui.update({...state,historical:true,runEnded:false});assert.match(d.querySelector('#status').textContent,/Archived/);assert.equal(d.querySelector('#stop').disabled,false);assert.equal(d.querySelector('#stop').textContent,'Cleanup options');
});

test('empty workspace opens picker once and refreshes respect dismissal',async t=>{
 const html=await readFile('packages/web/public/index.html','utf8');
 const js=await build({entryPoints:['packages/web/src/workspace.ts'],bundle:true,write:false,format:'iife',globalName:'Workspace',logLevel:'silent'});
 const dom=new JSDOM(html,{url:'http://127.0.0.1:1234/?history=02c9bdca87',runScripts:'outside-only'});t.after(()=>dom.window.close());
 const w=dom.window,d=w.document;w.eval(js.outputFiles[0].text+';window.W=Workspace;');
 let resolve;
 const ui=w.W.createWorkspace({request:()=>new Promise(r=>resolve=r),history:()=>{},ended:()=>{}});
 const menu=d.querySelector('#investigationMenu'),picker=d.querySelector('#investigationPicker');
 ui.empty();assert.equal(menu.hidden,false);
 d.body.dispatchEvent(new w.Event('pointerdown',{bubbles:true}));assert.equal(menu.hidden,true);
 resolve({investigations:[]});await new Promise(r=>setTimeout(r,0));assert.equal(menu.hidden,true);
 ui.empty();assert.equal(menu.hidden,true);resolve({investigations:[]});await new Promise(r=>setTimeout(r,0));assert.equal(menu.hidden,true);
 picker.click();assert.equal(menu.hidden,false);picker.click();assert.equal(menu.hidden,true);
 resolve({investigations:[]});await new Promise(r=>setTimeout(r,0));assert.equal(menu.hidden,true);assert.equal(picker.getAttribute('aria-expanded'),'false');
});

 test('missing snapshot retains ended run identity and disables End run',async t=>{
 const html=await readFile('packages/web/public/index.html','utf8');const js=await build({entryPoints:['packages/web/src/workspace.ts'],bundle:true,write:false,format:'iife',globalName:'Workspace',logLevel:'silent'});const dom=new JSDOM(html,{url:'http://127.0.0.1:1234/?history=f188abf6a0',runScripts:'outside-only'});t.after(()=>dom.window.close());const w=dom.window,d=w.document;w.eval(js.outputFiles[0].text+';window.W=Workspace;');let mutations=0;const ui=w.W.createWorkspace({request:async(path,body)=>{if(body)mutations++;return {investigations:[{id:'f188abf6a0',title:'Demo investigation',project:'/demo',runs:[{id:'f188abf6a0',status:'ended'}]}]};},history:()=>{},ended:()=>{}});ui.empty();await new Promise(r=>setTimeout(r,0));assert.equal(d.querySelector('#stop').disabled,true);assert.equal(d.querySelector('#stop').textContent,'Run ended');assert.match(d.querySelector('#investigationPicker').textContent,/Demo investigation/);assert.match(d.querySelector('#session').textContent,/f188abf6a0/);assert.equal(d.querySelector('#status').textContent,'Ended');d.querySelector('#stop').click();assert.equal(mutations,0);
 });

test('ended runs show dates and deletion requires explicit confirmation',async t=>{
 const html=await readFile('packages/web/public/index.html','utf8');const js=await build({entryPoints:['packages/web/src/workspace.ts'],bundle:true,write:false,format:'iife',globalName:'Workspace',logLevel:'silent'});const dom=new JSDOM(html,{url:'http://127.0.0.1:1234/?history=1111111111',runScripts:'outside-only'});t.after(()=>dom.window.close());const w=dom.window,d=w.document;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.eval(js.outputFiles[0].text+';window.W=Workspace;');const mutations=[];
 const ui=w.W.createWorkspace({request:async(path,body)=>{if(body){mutations.push({path,body});throw Error('Test deletion refused');}return {investigations:[{id:'1111111111',title:'Demo',project:'/demo',runs:[{id:'1111111111',status:'ended',created:'2026-09-21T10:00:00Z'},{id:'2222222222',status:'paused',created:'2026-09-21T11:00:00Z'}]}]};},history:()=>{},ended:()=>{}});
 ui.empty();await new Promise(r=>setTimeout(r,0));const deletes=[...d.querySelectorAll('#runList .rowActionList button')].filter(b=>b.textContent==='Delete saved run…');assert.equal(deletes.filter(b=>!b.disabled).length,1);assert.match(d.querySelector('.runDate').textContent,/Sep 21/);deletes[0].click();assert.equal(mutations.length,0);assert.match(d.querySelector('#workspaceDialogBody').textContent,/permanently removed/);[...d.querySelectorAll('#workspaceDialogBody button')].find(b=>b.textContent==='Delete run').click();await new Promise(r=>setTimeout(r,0));assert.deepEqual(JSON.parse(JSON.stringify(mutations)),[{path:'runs/delete',body:{id:'1111111111',confirmed:true}}]);assert.match(d.querySelector('#workspaceDialogBody').textContent,/Test deletion refused/);
});

test('agent attachment offers a single copyable prompt without mutating the run',async t=>{
 const html=await readFile('packages/web/public/index.html','utf8');const js=await build({entryPoints:['packages/web/src/workspace.ts'],bundle:true,write:false,format:'iife',globalName:'Workspace',logLevel:'silent'});const dom=new JSDOM(html,{url:'http://127.0.0.1:1234/?session=a2bfd1e34b',runScripts:'outside-only'});t.after(()=>dom.window.close());const w=dom.window,d=w.document;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};let copied='';Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async text=>{copied=text}}});w.eval(js.outputFiles[0].text+';window.W=Workspace;');let mutations=0;
 const ui=w.W.createWorkspace({request:async(path,body)=>{if(body)mutations++;return {investigations:[]}},history:()=>{},ended:()=>{}});const state={id:'a2bfd1e34b',status:'paused',state:{},project:'/demo',binary:'/demo/bin',agentConnected:false};ui.update(state);await new Promise(r=>setTimeout(r,0));const attach=d.querySelector('#reconnectAgent');assert.equal(attach.hidden,false);assert.equal(attach.textContent,'Attach to agent');attach.click();assert.match(d.querySelector('#workspaceDialogBody').textContent,/Paste this into your agent chat/);const copy=d.querySelector('#workspaceDialogBody button');assert.equal(copy.textContent,'Copy');copy.click();await new Promise(r=>setTimeout(r,0));assert.match(copied,/a2bfd1e34b/);assert.match(copied,/without resuming execution/);assert.equal(copy.textContent,'Copied');assert.equal(mutations,0);ui.update({...state,agentConnected:true});assert.equal(attach.hidden,true);ui.update({...state,historical:true});assert.equal(attach.hidden,true);
});

test('archive workspace never imports conversations from later runs',async t=>{
 const html=await readFile('packages/web/public/index.html','utf8'),js=await build({entryPoints:['packages/web/src/workspace.ts'],bundle:true,write:false,format:'iife',globalName:'Workspace'});
 const dom=new JSDOM(html,{url:'http://127.0.0.1/?history=1111111111',runScripts:'outside-only'});t.after(()=>dom.window.close());const w=dom.window;w.eval(js.outputFiles[0].text+';window.W=Workspace;');const calls=[];let items;
 const ui=w.W.createWorkspace({request:async path=>{calls.push(path);return {investigations:[{id:'1111111111',title:'Demo',project:'/demo',runs:[{id:'1111111111',ordinal:7,status:'ended'},{id:'2222222222',ordinal:9,status:'ended'}]}]};},history:v=>items=v,ended:()=>{}});
 await ui.load();assert.equal(calls.some(x=>x.startsWith('saved-run')),false);assert.equal(items.length,0);assert.equal(w.document.querySelector('.runItem').firstChild.textContent,'Run 7');const row=w.document.querySelector('#runList .runRow'),menu=row.querySelector('details');menu.open=true;row.querySelector('summary').focus();await ui.load();assert.equal(w.document.querySelector('#runList .runRow'),row);assert.equal(menu.open,true);assert.equal(w.document.activeElement,row.querySelector('summary'));
});

test('picker Escape restores focus and dialogs focus their primary field or cancel',async t=>{
 const html=await readFile('packages/web/public/index.html','utf8'),js=await build({entryPoints:['packages/web/src/workspace.ts'],bundle:true,write:false,format:'iife',globalName:'Workspace'});
 const dom=new JSDOM(html,{url:'http://127.0.0.1/?history=1111111111',runScripts:'outside-only'});t.after(()=>dom.window.close());const w=dom.window,d=w.document;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};w.eval(js.outputFiles[0].text+';window.W=Workspace;');
 const ui=w.W.createWorkspace({request:async()=>({investigations:[{id:'1111111111',title:'Demo',project:'/demo',runs:[{id:'1111111111',ordinal:1,status:'ended'}]}]}),history:()=>{},ended:()=>{}});await ui.load();const picker=d.querySelector('#investigationPicker');picker.click();d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(d.querySelector('#investigationMenu').hidden,true);assert.equal(d.activeElement,picker);
 d.querySelector('#newInvestigation').click();await new Promise(r=>setTimeout(r,0));assert.equal(d.activeElement,d.querySelector('#workspaceDialogBody input'));assert.equal(d.querySelector('#workspaceDialog').getAttribute('aria-labelledby'),'workspaceDialogTitle');d.querySelector('#closeWorkspaceDialog').click();
 [...d.querySelectorAll('#runList button')].find(b=>b.textContent==='Delete saved run…').click();await new Promise(r=>setTimeout(r,0));assert.equal(d.activeElement.textContent,'Cancel');assert.match(d.querySelector('#runList summary').getAttribute('aria-label'),/Run 1/);
});
