import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import {build} from 'esbuild';

test('stepping retains last pause, expansions and stable source; stale controls are disabled', async t => {
 const html = await readFile('ui/inspector/public/index.html','utf8');
 const js = await build({entryPoints:['ui/inspector/src/app.ts'],bundle:true,write:false,format:'iife',logLevel:'silent'});
 const dom = new JSDOM(html,{url:'http://127.0.0.1:1234',runScripts:'outside-only'});
 t.after(()=>dom.window.close());
 const w=dom.window,d=w.document;
 let tick, fail=false;
 let state={id:'test',owner:'browser',generation:1,status:'paused',state:{Pid:1},project:'/demo',binary:'/demo/bin',sourceIdentity:{match:'mismatch'},frame:0,goroutine:1,goroutines:[{id:1}],frames:[{file:'main.go',line:18,function:{name:'main.process'},Locals:[{name:'value',type:'S',children:[{name:'n',type:'int',value:'21'}]}]}],source:{file:'main.go',start:18,line:18,lines:['total += delta']}};
 w.setInterval=fn=>{tick=fn;return 1;};
 const calls=[];
 w.fetch=async(url,options)=>{calls.push({url,options});if(url==='/api/sessions')return {ok:true,json:async()=>({sessions:[{id:'test',project:'/demo',binary:'/demo/bin',status:'paused',owner:'browser',panel:'http://127.0.0.1:1234/'},{id:'other',project:'/other',binary:'/other/app',status:'paused',owner:'agent',binding:{name:'Pi'},panel:'http://127.0.0.1:5678/'},{id:'offline',project:'/old',binary:'/old/app',status:'offline'}]})};if(fail)throw Error('offline');return {ok:true,json:async()=>structuredClone(state)};};
 const flush=()=>new Promise(r=>setTimeout(r,0));
 w.eval(js.outputFiles[0].text);await flush();
 d.querySelector('#refreshSessions').click();await flush();
 assert.equal(d.querySelectorAll('.sessionRow').length,3);
 assert.equal(d.querySelectorAll('.endSession').length,2);
 w.confirm=()=>false;d.querySelector('.endSession').click();await flush();
 assert.ok(calls.every(c=>c.options.method==='GET'),'cancel must not terminate');
 assert.equal(d.querySelector('#sessionList a').href,'http://127.0.0.1:5678/');
 assert.match(d.querySelector('#sessionList').textContent,/Current/);
 assert.ok(calls.every(c=>c.options.method==='GET'),'listing must not mutate session');
 const source=d.querySelector('.sourceContent'),details=d.querySelector('#locals details'),frame=d.querySelector('#frames button');
 details.open=true;
 state={...state,status:'running',generation:2,frames:undefined,source:undefined,sourceIdentity:undefined,state:{}};tick();await flush();
 assert.equal(d.querySelector('.sourceContent'),source);
 assert.equal(d.querySelector('#locals details'),details);
 assert.equal(frame.disabled,true);
 assert.equal(d.querySelector('#sourceWarning').hidden,false,'warning must keep its space during a step');
 assert.match(d.querySelector('#session').textContent,/PID 1/);
 assert.equal(d.querySelector('main').dataset.executing,'true');
 assert.match(d.querySelector('#stopReason').textContent,/last pause/);
 state={...state,status:'paused',frames:[{file:'main.go',line:18,function:{name:'main.process'},Locals:[{name:'value',type:'S',children:[{name:'n',type:'int',value:'42'}]}]}],source:{file:'main.go',start:18,line:18,lines:['total += delta']}};tick();await flush();
 assert.equal(d.querySelector('.sourceContent'),source);
 assert.equal(d.querySelector('#locals details').open,true);
 assert.match(d.querySelector('#locals').textContent,/42/);
 assert.equal(d.querySelector('#frames button').disabled,false);
 const lines=Array.from({length:27},(_,i)=>'// line '+(i+10));
 state={...state,source:{file:'main.go',start:10,line:22,lines}};tick();await flush();
 const stableCode=d.querySelector('.sourceContent');
 state={...state,generation:3,source:{file:'main.go',start:11,line:23,lines:[...lines.slice(1),'// line 37']}};tick();await flush();
 assert.equal(d.querySelector('.sourceContent'),stableCode,'overlapping step should move marker without replacing code');
 assert.equal(d.querySelector('.sourceHighlight.current').dataset.line,'23');
 fail=true;tick();await flush();assert.equal(d.querySelector('.sourceContent'),stableCode);assert.equal(d.querySelector('#frames button').disabled,true);
 fail=false;tick();await flush();assert.equal(d.querySelector('#frames button').disabled,false);
});
