import type {Snapshot,CommentThread} from '../../client/src/models';
import {createClient} from '../../client/src/index';
interface Run {ordinal?:number;launchError?:string;launchAvailable?:boolean;id:string;project:string;binary:string;status:string;panel?:string;created?:string;debuggerPid?:number;targetPid?:number;adapter?:string;protocol?:string}
interface Investigation {created?:string;id:string;title:string;project:string;runs:Run[]}
type Hooks={runs?:(names:Record<string,string>)=>void;request:<T>(path:string,body?:Record<string,unknown>)=>Promise<T>;history:(items:(CommentThread&{run?:string})[])=>void;ended:()=>void};
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const el=(tag:string,text='',cls='')=>{const e=document.createElement(tag);e.textContent=text;e.className=cls;return e;};
const compactDate=(s?:string)=>s&&Number.isFinite(Date.parse(s))?new Date(s).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}):'Date unavailable';
const date=(s?:string)=>s&&Number.isFinite(Date.parse(s))?new Date(s).toLocaleString(undefined,{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'Date unavailable';
const base=(s:string)=>s.split('/').pop()||s;
export function createWorkspace(hooks:Hooks){
 let lastPID:number|undefined;
 const rows=new Map<string,{key:string;node:HTMLElement}>();
 function cachedRow(id:string,key:string,build:()=>HTMLElement){
  const old=rows.get(id);if(old?.key===key)return old.node;
  const node=build();const menu=old?.node.querySelector<HTMLDetailsElement>('.rowActions');
  if(menu?.open){const next=node.querySelector<HTMLDetailsElement>('.rowActions');if(next)next.open=true;}
  if(old?.node.contains(document.activeElement)){
   const focused=document.activeElement as HTMLElement;const label=focused.textContent;
   queueMicrotask(()=>{const next=[...node.querySelectorAll<HTMLElement>('button,summary')].find(e=>e.textContent===label&&!(e as HTMLButtonElement).disabled);(next||node.querySelector<HTMLElement>('summary'))?.focus();});
  }
  rows.set(id,{key,node});return node;
 }
 function reconcile(parent:HTMLElement,nodes:HTMLElement[]){for(let i=0;i<nodes.length;i++)if(parent.children[i]!==nodes[i])parent.insertBefore(nodes[i],parent.children[i]||null);while(parent.children.length>nodes.length)parent.lastElementChild!.remove();}

 let initialPickerHandled=false;
 const selectedID=new URLSearchParams(location.search).get('history')||new URLSearchParams(location.search).get('session');
 let state:Snapshot|undefined,groups:Investigation[]=[],current:Investigation|undefined,disconnected=false,loaded='',loading=false,hasWorkspace=true;
 const dialog=$<HTMLDialogElement>('workspaceDialog');let dialogTrigger:HTMLElement|null=null;dialog.addEventListener('close',()=>dialogTrigger?.focus());
 function open(title:string){if(!dialog.open)dialogTrigger=document.activeElement as HTMLElement;$('workspaceDialogTitle').textContent=title;const body=$('workspaceDialogBody');body.replaceChildren();if(!dialog.open)dialog.showModal();queueMicrotask(()=>{(body.querySelector<HTMLElement>('input,textarea')||[...body.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.textContent==='Cancel')||body.querySelector<HTMLElement>('button'))?.focus();});return body;}
 function button(parent:HTMLElement,label:string,fn:()=>void){const b=el('button',label) as HTMLButtonElement;b.onclick=fn;parent.append(b);return b;}
 function error(e:unknown){const text=e instanceof Error?e.message:String(e);$('sessionsError').textContent=text;$('sessionsError').hidden=false;}
 function visit(run:Run){if(run.id===state?.id&&!state.historical)return;const url=run.panel?new URL(run.panel):new URL(location.href);if(url.protocol!=='http:'||url.hostname!=='127.0.0.1'||url.username||url.password){error('Invalid local run URL');return;}if(!run.panel){url.searchParams.delete('session');url.searchParams.set('history',run.id);}location.href=url.href;}
 function runNumber(id:string){const run=current?.runs.find(r=>r.id===id);return run?.ordinal?String(run.ordinal):id;}
 function draw(){
  current=groups.find(g=>g.runs.some(r=>r.id===(state?.id||selectedID)));$('investigationPicker').textContent=(current?.title||'Investigations')+' ▾';$('projectName').textContent=current?base(current.project):'';const stamp=$('investigationDate');stamp.textContent=current?.created?'Started '+date(current.created):'';stamp.title=current?.created?new Date(current.created).toString():'';if(current?.created)stamp.setAttribute('datetime',current.created);
  hooks.runs?.(Object.fromEntries(current?.runs.map(r=>[r.id,runNumber(r.id)])||[]));
  const groupRows:HTMLElement[]=[];for(const g of groups){const row=cachedRow('g:'+g.id,JSON.stringify([g,g===current]),()=>{const row=el('div','','sessionRow');const b=button(row,g.title,()=>{const run=g.runs.find(r=>r.id===state?.id)||[...g.runs].reverse().find(r=>r.panel)||g.runs.at(-1);if(run)visit(run);$('investigationMenu').hidden=true;});b.append(el('small',`${base(g.project)} · ${g.runs.length} runs · ${date(g.runs.at(-1)?.created)}${g===current?' · Current':''}`));actions(row,[{label:'Delete investigation…',disabled:g.runs.some(r=>r.status!=='ended'),reason:'End every run before deleting this investigation.',run:()=>deleteInvestigation(g)}]);return row;});groupRows.push(row);}reconcile($('sessionList'),groupRows);
  const runRows:HTMLElement[]=[];$('sessionCount').textContent=String(current?.runs.length||0);current?.runs.forEach(r=>{const row=cachedRow('r:'+r.id,JSON.stringify([r,runNumber(r.id),r.id===(state?.id||selectedID),hasWorkspace]),()=>{const row=el('div','','runRow');const b=button(row,`Run ${runNumber(r.id)}`,()=>visit(r));b.className='runItem'+(r.id===(state?.id||selectedID)?' selected':'');b.append(el('small',`${r.launchError?'Launch failed':r.status==='offline'?'Connection unavailable':r.status}`));b.append(el('small',compactDate(r.created),'runDate'));actions(row,[{label:'Run again',disabled:!hasWorkspace||r.launchAvailable===false,reason:'This older run has no saved launch arguments.',run:()=>runAgain(r)},{label:'Delete saved run…',disabled:r.status!=='ended'||!hasWorkspace,reason:'End this run before deleting its saved evidence.',run:()=>deleteRun(r)}]);if(!r.panel&&r.status==='offline')b.onclick=()=>recovery(r);return row;});runRows.push(row);});reconcile($('runList'),runRows);
  if(!state){const run=current?.runs.find(r=>r.id===selectedID);const ended=run?.status==='ended';$('stop').textContent=ended?'Run ended':run?'Cleanup options':'End run';$<HTMLButtonElement>('stop').disabled=!run||ended;$('session').textContent=run?`Run ${runNumber(run.id)} · ${run.id}`:'Select an investigation or start a new one';if(run){$('status').textContent=ended?'Program · Ended':'Program · Not verified';$('debuggerStatus').textContent='Details';$('agentStatus').textContent='Agent · Not connected';}}
  $<HTMLButtonElement>('runAgain').disabled=!(state||current)||!hasWorkspace;syncHeader();$<HTMLButtonElement>('newInvestigation').disabled=!hasWorkspace;
 }
 async function load(){if(loading)return;loading=true;$<HTMLButtonElement>('refreshSessions').disabled=true;try{let result:{investigations:Investigation[]};try{result=await hooks.request('workspace');if(!Array.isArray(result.investigations))throw Error('Workspace API unavailable');hasWorkspace=true;}catch{const old=await hooks.request<{sessions:Run[]}>('sessions');if(!Array.isArray(old.sessions))throw Error('Could not load investigations');result={investigations:old.sessions.map(r=>({id:r.id,title:base(r.binary),project:r.project,runs:[r]}))};hasWorkspace=false;}
  groups=result.investigations;draw();$('sessionsError').hidden=true;
  if(state?.historical||new URLSearchParams(location.search).has('history')){hooks.history([]);}
  else if(current&&hasWorkspace){const prior=current.runs.filter(r=>r.id!==state?.id);const snapshots=await Promise.allSettled(prior.map(r=>hooks.request<{discussion:{threads:CommentThread[]}}>('saved-run?id='+encodeURIComponent(r.id)).then(s=>s.discussion.threads.map(t=>({...t,run:r.id})))));const all:(CommentThread&{run?:string})[]=[];for(const result of snapshots)if(result.status==='fulfilled')all.push(...result.value);hooks.history(all);}
 }catch(e){error(e);}finally{loading=false;$<HTMLButtonElement>('refreshSessions').disabled=false;}}
 function actions(parent:HTMLElement,items:{label:string;disabled?:boolean;reason?:string;run:()=>void}[]){const menu=document.createElement('details');menu.className='rowActions';const summary=el('summary','⋯');summary.setAttribute('aria-label','Actions for '+(parent.querySelector('button')?.firstChild?.textContent||'item'));const list=el('div','','rowActionList');menu.append(summary,list);for(const item of items){const b=button(list,item.label,()=>{menu.open=false;item.run();});b.disabled=!!item.disabled;if(item.disabled&&item.reason){b.title=item.reason;list.append(el('small',item.reason));}}menu.addEventListener('toggle',()=>{if(menu.open){const rect=summary.getBoundingClientRect();list.style.position='fixed';list.style.left=Math.max(8,Math.min(rect.left,window.innerWidth-210))+'px';list.style.right='auto';list.style.top=Math.min(rect.bottom,window.innerHeight-list.offsetHeight-8)+'px';}if(menu.open)document.querySelectorAll<HTMLDetailsElement>('.rowActions').forEach(other=>{if(other!==menu)other.open=false});});menu.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.open=false;summary.focus();}});parent.append(menu);}
 function deleteInvestigation(group:Investigation){const body=open('Delete investigation?');body.append(el('p',`Delete “${group.title}” and its ${group.runs.length} runs? All their saved logs, snapshots and discussions will be permanently removed. This cannot be undone.`));button(body,'Cancel',()=>dialog.close());const b=button(body,'Delete investigation',()=>{b.disabled=true;void hooks.request('investigations/delete',{id:group.id,confirmed:true}).then(()=>{dialog.close();if(group.id===current?.id)location.href=location.origin+'/';else void load();}).catch(e=>{body.append(el('p',String(e)));b.disabled=false;});});}
 function deleteRun(run:Run){const body=open('Delete saved run?');body.append(el('p',`Delete run ${run.id} from ${date(run.created)}? Its saved snapshots, log, and discussion copy will be permanently removed. Copies of conversations continued in other runs remain. This cannot be undone.`));button(body,'Cancel',()=>dialog.close());const confirm=button(body,'Delete run',()=>{confirm.disabled=true;void hooks.request('runs/delete',{id:run.id,confirmed:true}).then(()=>{dialog.close();if(run.id===(state?.id||selectedID)){const next=current?.runs.find(r=>r.id!==run.id);if(next)visit(next);else location.href=location.origin+'/';}else void load();}).catch(e=>{body.append(el('p',String(e)));confirm.disabled=false;});});}
 function syncHeader(){const run=current?.runs.find(r=>r.id===(state?.id||selectedID));const archived=!!state?.historical||!!new URLSearchParams(location.search).get('history');const ended=state?.runEnded||run?.status==='ended';$('runTitle').textContent=run?'Run '+runNumber(run.id):state?'Run '+runNumber(state.id):'Select a run';$('runDate').textContent=run?date(run.created):'';$('status').textContent=disconnected?'Connection lost':ended?'Ended':archived?'Archived':state?state.status==='paused'?'Paused':state.status==='running'?'Running':'Exited':run?'Not verified':'No run';$('runLocation').textContent=!archived&&state?.status==='paused'&&state.source?base(state.source.file)+':'+state.source.line:'';$('debuggerStatus').textContent='Details';$<HTMLButtonElement>('debuggerStatus').disabled=!run&&!state;$('stop').hidden=ended||(!run&&!state);$('headerRunAgain').hidden=(!archived&&state?.status!=='exited')||!run;$<HTMLButtonElement>('headerRunAgain').disabled=!hasWorkspace||run?.launchAvailable===false;$<HTMLButtonElement>('runAgain').disabled=!hasWorkspace||run?.launchAvailable===false||(!run&&!state);$('headerRunAgain').title=run?.launchAvailable===false?'This older run has no saved launch arguments.':'';$('reconnectAgent').hidden=archived||state?.agentConnected===true;$('agentStatus').hidden=archived;if(run){const label=`Run ${runNumber(run.id)} · ${run.id}`+(!archived?` · PID ${lastPID||'—'}`:'');if($('session').textContent!==label)$('session').textContent=label;}}
 function recovery(run?:Run){const id=run?.id||state?.id;if(!id)return;const body=open('Recover debugger connection');body.append(el('p','Connection lost does not prove that the debugger or target has stopped. You can recover and end this run from a terminal without an agent.'),el('pre',`brote recover ${id}\nagentdebugger end-session ${id} --confirmed`));}
 function agent(){
  if(!state)return;
  const body=open('Attach to agent');
  const prompt=`Connect to Brote run ${state.id} in ${state.project}. Inspect the current pause without resuming execution. Enable the event bridge for inline questions if available.`;
  body.append(el('p','Paste this into your agent chat'),el('pre',prompt));
  const copy=button(body,'Copy',()=>{void navigator.clipboard.writeText(prompt).then(()=>{copy.textContent='Copied';}).catch(()=>{copy.textContent='Select and copy the text above';});});
 }
 function details(){const run=current?.runs.find(r=>r.id===(state?.id||selectedID));if(!run&&!state)return;const body=open('Debugger details'),dl=el('dl');for(const [k,v] of [['Adapter',state?.debugger?.adapter||run?.adapter||'Not reported'],['Protocol',state?.debugger?.protocol||run?.protocol||'Not reported'],['Connection',disconnected?'Connection lost':state?.historical||!state?'Historical record':'Connected'],['Debugger PID',String(state?.debugger?.pid||run?.debuggerPid||'Not reported')],['Target PID',String(state?.state.Pid||run?.targetPid||'Not reported')]])dl.append(el('dt',k),el('dd',v));body.append(dl);if(disconnected)button(body,'Recovery instructions',()=>recovery());}
 async function start(body:Record<string,unknown>,b:HTMLButtonElement){b.disabled=true;const err=el('p');$('workspaceDialogBody').append(err);try{const api=createClient({baseURL:location.origin,timeoutMs:30000});const result=await api.request<{panel:string;id:string}>('runs/start',body);const url=new URL(result.panel);if(url.protocol!=='http:'||url.hostname!=='127.0.0.1')throw Error('Invalid launch URL');location.href=url.href;}catch(e){err.textContent=e instanceof Error?e.message:String(e);b.disabled=false;}}
 function runAgain(run?:Run){const id=run?.id||state?.id||selectedID;const binary=run?.binary||state?.binary||current?.runs.find(r=>r.id===id)?.binary;if(!id||!binary)return;const body=open('Run again');body.append(el('p','Start a new paused run with the saved executable and arguments. Breakpoints and agent connections are not copied.'),el('pre',binary));const b=button(body,'Start run',()=>void start({run:id},b));}
 $('runAgain').onclick=()=>runAgain();$('headerRunAgain').onclick=()=>runAgain();
 $('newInvestigation').onclick=()=>{const body=open('New investigation');const fields:Record<string,HTMLInputElement>={};for(const [id,label,value] of [['title','Investigation title',''],['project','Project directory',state?.project||''],['binary','Precompiled executable',state?.binary||'']]){const row=el('label',label),input=document.createElement('input');input.value=value;input.required=true;row.append(input);body.append(row);fields[id]=input;}body.append(el('p','Starts the executable paused. No compilation or agent execution is requested.'));const b=button(body,'Start investigation',()=>{if(Object.values(fields).every(f=>f.reportValidity()))void start(Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,v.value])),b);});};
 $('stop').onclick=()=>{if(!state){const run=current?.runs.find(r=>r.id===selectedID);if(run&&run.status!=='ended')recovery(run);return;}if(state.historical){if(!state.runEnded)recovery();return;}if(disconnected){recovery();return;}const body=open('End this run?');body.append(el('p','Stops the launched program and its debugger. Investigation discussions and saved snapshots are retained. No agent connection is required.'));button(body,'Cancel',()=>dialog.close());const b=button(body,'End run',()=>{b.disabled=true;void hooks.request('sessions/stop',{id:state!.id,confirmed:true}).then(()=>{dialog.close();hooks.ended();void load();}).catch(e=>{body.append(el('p',String(e)));b.disabled=false;});});};
 $('debuggerStatus').onclick=details;$('reconnectAgent').onclick=agent;$('closeWorkspaceDialog').onclick=()=>dialog.close();$('refreshSessions').onclick=()=>void load();$('investigationPicker').onclick=()=>{const menu=$('investigationMenu');menu.hidden=!menu.hidden;$('investigationPicker').setAttribute('aria-expanded',String(!menu.hidden));if(!menu.hidden)void load();};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!dialog.open&&!$('investigationMenu').hidden){$('investigationMenu').hidden=true;$('investigationPicker').setAttribute('aria-expanded','false');$('investigationPicker').focus();}});document.addEventListener('pointerdown',e=>{document.querySelectorAll<HTMLDetailsElement>('.rowActions[open]').forEach(m=>{if(!m.contains(e.target as Node))m.open=false;});if(!$('investigationMenu').contains(e.target as Node)&&!$('investigationPicker').contains(e.target as Node)){$('investigationMenu').hidden=true;$('investigationPicker').setAttribute('aria-expanded','false');}});
 return {load,update(s:Snapshot,lost=false){if(state?.id!==s.id)lastPID=undefined;const changed=state?.status!==s.status;state=s;if(current){const run=current.runs.find(r=>r.id===s.id);if(run&&!s.historical)run.status=s.status;if(changed)draw();}if(lost)$('agentStatus').textContent='Agent · Connection unverified';lastPID=s.state.Pid||lastPID;disconnected=lost;$('debuggerStatus').textContent='Debugger · '+(lost?'Connection lost':s.historical?(s.runEnded?'Stopped':'Not verified'):s.debugger?.status==='stopped'?'Stopped':'Connected');$<HTMLButtonElement>('reconnectAgent').hidden=s.agentConnected===true||!!s.historical;$<HTMLButtonElement>('stop').disabled=!!s.historical&&!!s.runEnded;$('stop').textContent=s.historical?(s.runEnded?'Run ended':'Cleanup options'):lost?'Cleanup options':'End run';if(loaded!==s.id){loaded=s.id;void load();} const footer=`Run ${runNumber(s.id)} · ${s.id}`+(!s.historical?` · PID ${lastPID||'—'}`:'');if($('session').textContent!==footer)$('session').textContent=footer;syncHeader();},empty(){$<HTMLButtonElement>('stop').disabled=true;if(!initialPickerHandled){initialPickerHandled=true;$('investigationMenu').hidden=false;$('investigationPicker').setAttribute('aria-expanded','true');}void load();if(!selectedID)$('session').textContent='Select an investigation or start a new one';}};
}
